Flush on exit in time_buffered
Rewrite time_buffered into functions
Always use native time_buffered

diff --git a/tools/test_runner/time_buffered b/tools/test_runner/time_buffered
--- a/tools/test_runner/time_buffered
+++ b/tools/test_runner/time_buffered
@@ -1,33 +1,46 @@
 #!/usr/bin/env bash
 
-# Bash version
-function time_buffered
+function writer
 {
-    delay=$1
+    local sleep_pidfile=$1
     while read line; do
         printf "%d %s\n" "$(date +%s)" "$line"
-    done | while read ts line; do
+    done
+    # Oh, the pipe is closed, flush.
+    # Interrupt sleeping.
+    local sleep_pid=$(cat "$sleep_pidfile" || true)
+    # Signal the process below to set delay=0.
+    if [ -z "$sleep_pidfile" ]; then
+        kill $sleep_pid &2>/dev/null || true
+    fi
+}
+
+function reader
+{
+    local delay=$1
+    local sleep_pidfile=$2
+    while read ts line; do
         now=$(date +%s)
         if (( now - ts < delay)); then
-            sleep $(( now - ts ))
+            sleep $(( now - ts )) &
+            local sleep_pid="$!"
+            echo "$sleep_pid" > "$sleep_pidfile"
+            # If wait (and sleep) fails, most likely it has been killed by kill above
+            wait "$sleep_pid" || delay=0
         fi
         printf "%s\n" "$line"
     done
 }
 
-# Try to compile
-#if test ! -d _build/.test_runner/delay; then
-#    mkdir -p _build/.test_runner
-#    git clone "https://github.com/arcusfelis/delay.git" _build/.test_runner/delay
-#    make -C _build/.test_runner/delay || echo "Failed to compile C version of delay"
-#fi
+# Bash version
+function time_buffered
+{
+    local sleep_pidfile=$(mktemp)
+    local delay=$1
+    writer "$sleep_pidfile" | reader "$delay" "$sleep_pidfile"
+    rm -f "$sleep_pidfile"
+}
 
 SECONDS=$1
 
-if test -f _build/.test_runner/delay/delay; then
-    # 3k per second limit due to travis not working good with fast output
-    _build/.test_runner/delay/delay "$SECONDS"
-else
-    echo "Fallback for bash version of time_buffered"
-    time_buffered "$SECONDS"
-fi
+time_buffered "$SECONDS"
